<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="E0366482" ignored="0" name="Test" tests="2" failures="1" timestamp="31 Jan 2018 11:58:18 GMT" time="0.046" errors="0">
  <testcase name="Dummy_test_to_fail" time="0.013" classname="MavenTest.TC001">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at MavenTest.TC001.Dummy_test_to_fail(TC001.java:14)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Dummy_test_to_fail -->
  <testcase name="Dummy_test_to_pass" time="0.001" classname="MavenTest.TC001"/>
</testsuite> <!-- Test -->
